version: '3'

services:
  ubuntu_mariadb:
    build: 
      context: ./
      dockerfile: Dockerfile_MariaDB
    #image: mariadb
    container_name: mariadb_ubuntu
    environment: 
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33060:3306"
    restart: on-failure  


  ubuntu_essentials:
    build: 
      context: ./
      dockerfile: Dockerfile
      #image: diogodias2/bionic_essentials
    container_name: bionic_essentials_ssh
    links:
      - ubuntu_mariadb
    ports:
        - "22:22"
        - "80:80"
        - "443:443"
        - "3306:33060"
    stdin_open: true
    tty: true
      
   

